# Generated by Django 2.1.3 on 2019-03-09 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mapData',
            fields=[
                ('URN', models.IntegerField(primary_key=True, serialize=False)),
                ('LA', models.CharField(max_length=128, null=True)),
                ('EstablishmentName', models.CharField(max_length=128, null=True)),
                ('TypeOfEstablishment', models.CharField(max_length=128, null=True)),
                ('PhaseOfEducation', models.CharField(max_length=128, null=True)),
                ('OfficialSixthForm', models.CharField(max_length=128, null=True)),
                ('Gender', models.CharField(max_length=128, null=True)),
                ('AdmissionsPolicy', models.CharField(max_length=128, null=True)),
                ('NumberOfPupils', models.CharField(max_length=128, null=True)),
                ('NumberOfBoys', models.CharField(max_length=128, null=True)),
                ('NumberOfGirls', models.CharField(max_length=128, null=True)),
                ('Street', models.CharField(max_length=128, null=True)),
                ('Locality', models.CharField(max_length=128, null=True)),
                ('Town', models.CharField(max_length=128, null=True)),
                ('County', models.CharField(max_length=128, null=True)),
                ('Postcode', models.CharField(max_length=128, null=True)),
                ('SchoolWebsite', models.CharField(max_length=128, null=True)),
                ('TelephoneNum', models.CharField(max_length=128, null=True)),
                ('HeadTitle', models.CharField(max_length=128, null=True)),
                ('HeadFirstName', models.CharField(max_length=128, null=True)),
                ('HeadLastName', models.CharField(max_length=128, null=True)),
                ('OfstedRating', models.CharField(max_length=128, null=True)),
                ('Longitude', models.FloatField(max_length=128, null=True)),
                ('Latitude', models.FloatField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='schoolPerformance',
            fields=[
                ('URN', models.IntegerField(primary_key=True, serialize=False)),
                ('EstablishmentName', models.CharField(max_length=128, null=True)),
                ('Gcse_average_low', models.CharField(max_length=128, null=True)),
                ('Gcse_average_high', models.CharField(max_length=128, null=True)),
                ('Average_Ebacc', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('list', models.ManyToManyField(related_name='lists', to='school.mapData')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
